layout_spectrum: 0.8447955760639161
typography_spectrum: 0.5883670144248754
color:
  brandStrength: 0.4289821849670261
  lightness: 0.4970488240942359
  saturation: 0.7455188028980047
  rhythmicContrast: 0.7526439561042935
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
name: Ryan Burchfield Photography
navigation:
  - name: ' '
    id: 04607152-c21f-4944-9c45-efc7a12c324a
    type: content
  - name: About
    id: 9cb7402c-50f7-4572-83ff-f9762ecf6634
    type: content
