layout_spectrum: 0.8447955760639161
typography_spectrum: 0.5883670144248754
color:
  brandStrength: 0.4289821849670261
  lightness: 0.4970488240942359
  saturation: 0.7455188028980047
  rhythmicContrast: 0.7526439561042935
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Ryan Burchfield Photography
