layout_spectrum: 0.8447955760639161
typography_spectrum: 0.5883670144248754
color:
  brandStrength: 0.4289821849670261
  lightness: 0.4970488240942359
  saturation: 0.7455188028980047
  rhythmicContrast: 0.7526439561042935
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
name: Ryan Burchfield Photography
navigation:
  - name: Portfolio
    id: 95e5e5de-3e26-4c67-9e20-3b0d28c067cb
    type: content
